services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  get_set_method_normalizer:
    class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
    tags: [ 'serializer.normalizer' ]

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

  App\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  app.monolog.processor.web:
    class: App\Helpers\Logger
    tags:
      - { name: monolog.processor, method: processRecord }

  Redis:
      class: Redis
      calls:
          - connect:
              - '%env(REDIS_HOST)%'
              - '%env(int:REDIS_PORT)%'

  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
      arguments:
          - '@Redis'